version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - './docker-entrypoint-initdb.d/pg-init.sql:/docker-entrypoint-initdb.d/1-pg-init.sql'
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db
    volumes:
      - ./server.json:/pgadmin4/servers.json

  cache:
    image: redis:8.0.1
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - cache:/data

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - '4566:4566'
      - '4571:4571'
    environment:
      - SERVICES=sqs,events,scheduler
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - './localstack/init:/etc/localstack/init/ready.d'
      - "/var/run/docker.sock:/var/run/docker.sock"

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nest-app
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #     - cache
  #     - localstack

volumes:
  cache:
    driver: local
